export const PAGE_URL_PATHS = {
  HOME: "",
  SOFA_SET: "sofa-set",
  TABLE_LAMP: "table-lamps",
  DINING_TABLES: "dining-table",
  LIGHTING: "lighting",
  LUXURY_ACCESSORIES_DECOR: "luxury-accessories-decor",
  SIDE_STOOL: "side-stool",
  WALL_FRAMES: "wall-frames",
  WALL_ARTS_AND_CLOCK: "wall-arts-and-clock",
  DIFFUSERS_AND_CANDLES: "diffusers-and-candles",
  MIRRORS: "mirrors",
  CONTACT_US: "contact-us",
  SERVICE: "service", 
};

export const navLinks = [
  { label: "Home", href: `/${PAGE_URL_PATHS.HOME}` },
  { label: "Sofa Set", href: `/${PAGE_URL_PATHS.SOFA_SET}` },
  { label: "Table Lamps", href: `/${PAGE_URL_PATHS.TABLE_LAMP}` },
  { label: "Dining Table", href: `/${PAGE_URL_PATHS.DINING_TABLES}` },
  { label: "Lighting", href: `/${PAGE_URL_PATHS.LIGHTING}` },
  { label: "Luxury Accessories/Decor", href: `/${PAGE_URL_PATHS.LUXURY_ACCESSORIES_DECOR}` },
  { label: "Side Stool", href: `/${PAGE_URL_PATHS.SIDE_STOOL}` },
  { label: "Wall Frames", href: `/${PAGE_URL_PATHS.WALL_FRAMES}` },
  { label: "Wall Art And Clock", href: `/${PAGE_URL_PATHS.WALL_ARTS_AND_CLOCK}` },
  { label: "Diffusers and Candle", href: `/${PAGE_URL_PATHS.DIFFUSERS_AND_CANDLES}` },
  { label: "Mirrors", href: `/${PAGE_URL_PATHS.MIRRORS}` },
  { label: "Service", href: `/${PAGE_URL_PATHS.SERVICE}` }, 
  { label: "Contact Us", href: `/${PAGE_URL_PATHS.CONTACT_US}` },
];
