import type { Metadata } from "next";
import { Noto_Serif } from "next/font/google";
import "./globals.css";
import MaxWidthContainer from "@/components/shared/MaxWidthContainer";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";


const notoSerif = Noto_Serif({
  variable: "--font-noto-serif",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Cuddley Interiors",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${notoSerif.variable} antialiased`}
      >
        <MaxWidthContainer>
          <Navbar />
          {children}
          <Footer />
        </MaxWidthContainer>
      </body>
    </html>
  );
}
